version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  api:
    image: essence_api
    restart: always
    env_file:
      - .env
    ports:
      - "5011:5010"
    depends_on:
      - database