version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "5011:5010"
    depends_on:
      - database
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "90:80"
    depends_on:
      - database
      - api
