name: Essence CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 20.x
        cache: 'npm'
# Restore dependencies
    - name: Restore .NET dependencies
      run: dotnet restore
      working-directory: api
    - name: Restore Node.js dependencies
      run: npm ci
      working-directory: app
# Build      
    - name: Build Web API
      run: dotnet build --no-restore
      working-directory: api
    - name: Build Web application
      run: npm run build --if-present
      working-directory: app
